name: budget_buddy
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  lottie: ^2.2.0
  http: ^0.13.4
  flutter_svg: ^2.0.4
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  external_app_launcher: ^3.1.0
  flutter_tts: ^3.6.3
  delayed_display: ^2.0.0
  url_launcher: ^6.1.10
  jwt_decoder: ^2.0.1
  fl_chart: ^0.61.0
  material_dialogs:
  anim_search_bar: ^2.0.3

  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  flutter_local_notifications: ^13.0.0

  # Syncfusion dependencies
  syncfusion_flutter_calendar: ^21.1.38
  syncfusion_flutter_sliders: ^21.1.35
  syncfusion_flutter_charts: ^21.1.38
  syncfusion_flutter_gauges: ^21.1.38
  dropdown_button2: ^1.8.1
  candlesticks: ^2.1.0
  shared_preferences: ^2.0.20
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  drop_shadow: ^0.0.1+4
  cached_network_image: ^3.3.1
  animated_bottom_navigation_bar: ^1.2.0
  line_awesome_flutter: ^2.0.0
  share_plus: ^6.3.1
  google_ml_kit: ^0.13.0
  image_picker: ^0.8.7+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/extras/
