import 'package:flutter/material.dart';

List<Map<String, dynamic>> hobbies = [
{"name": "Reading", "icon": Icons.book},
{"name": "Writing", "icon": Icons.create},
{"name": "Drawing", "icon": Icons.brush},
{"name": "Painting", "icon": Icons.palette},
{"name": "Knitting", "icon": Icons.scatter_plot},
{"name": "Crocheting", "icon": Icons.zoom_out_map},
{"name": "Sewing", "icon": Icons.add_shopping_cart},
{"name": "Cooking", "icon": Icons.restaurant},
{"name": "Baking", "icon": Icons.cake},
{"name": "Gardening", "icon": Icons.local_florist},
{"name": "Swimming", "icon": Icons.pool},
{"name": "Running", "icon": Icons.directions_run},
{"name": "Jogging", "icon": Icons.directions_run},
{"name": "Cycling", "icon": Icons.directions_bike},
{"name": "Dancing", "icon": Icons.music_note},
{"name": "Singing", "icon": Icons.music_note},
{"name": "Playing", "icon": Icons.sports},
{"name": "Gaming", "icon": Icons.videogame_asset},
{"name": "Hunting", "icon": Icons.my_location},
{"name": "Woodworking", "icon": Icons.format_shapes},
{"name": "Metalworking", "icon": Icons.build},
{"name": "Sculpting", "icon": Icons.panorama},
{"name": "Photography", "icon": Icons.camera_alt},
{"name": "Traveling", "icon": Icons.flight_takeoff},
{"name": "Collecting", "icon": Icons.collections},
{"name": "Listening", "icon": Icons.audiotrack},
{"name": "Watching", "icon": Icons.theaters},
{"name": "Acting", "icon": Icons.people},
{"name": "Improvising", "icon": Icons.lightbulb_outline},
{"name": "Magic", "icon": Icons.stars},
{"name": "Juggling", "icon": Icons.blur_on},
{"name": "Playing", "icon": Icons.sports},
{"name": "Acting", "icon": Icons.people},
{"name": "Singing", "icon": Icons.music_note},
{"name": "Listening", "icon": Icons.audiotrack},
{"name": "Watching", "icon": Icons.theaters},
{"name": "Gardening", "icon": Icons.local_florist},
{"name": "Hunting", "icon": Icons.my_location},
{"name": "Biking", "icon": Icons.directions_bike},
{"name": "Running", "icon": Icons.directions_run},
{"name": "Swimming", "icon": Icons.pool},
];

