import 'package:flutter/material.dart';

final List<Map<String, dynamic>> techStack = [
  {"name": "Java", "icon": Icons.computer},
  {"name": "Python", "icon": Icons.code_outlined},
  {"name": "JavaScript", "icon": Icons.language},
  {"name": "Ruby", "icon": Icons.widgets},
  {"name": "PHP", "icon": Icons.web_asset},
  {"name": "C++", "icon": Icons.memory},
  {"name": "C#", "icon": Icons.developer_board},
  {"name": "Go", "icon": Icons.dashboard},
  {"name": "Kotlin", "icon": Icons.android},
  {"name": "Swift", "icon": Icons.phone_iphone},
  {"name": "TypeScript", "icon": Icons.edit},
  {"name": "Scala", "icon": Icons.storage},
  {"name": "Rust", "icon": Icons.build},
  {"name": "Haskell", "icon": Icons.timeline},
  {"name": "Lua", "icon": Icons.lightbulb_outline},
  {"name": "Perl", "icon": Icons.fiber_manual_record},
  {"name": "Shell", "icon": Icons.code},
  {"name": "PowerShell", "icon": Icons.power},
  {"name": "Bash", "icon": Icons.code_rounded},
  {"name": "Dart", "icon": Icons.extension},
  {"name": "Objective-C", "icon": Icons.phone_iphone},
  {"name": "Groovy", "icon": Icons.layers},
  {"name": "Erlang", "icon": Icons.nature_people},
  {"name": "Clojure", "icon": Icons.filter},
  {"name": "Assembly", "icon": Icons.settings_input_svideo},
  {"name": "Visual Basic", "icon": Icons.desktop_windows},
  {"name": "SQL", "icon": Icons.storage},
  {"name": "NoSQL", "icon": Icons.collections_bookmark},
];
