// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJsfhmDQ4HYeTAOePVT5VrBKQEqiJdNe0',
    appId: '1:726361486193:web:b781773490c08b8bccfcd0',
    messagingSenderId: '726361486193',
    projectId: 'budget-buddy-aac53',
    authDomain: 'budget-buddy-aac53.firebaseapp.com',
    storageBucket: 'budget-buddy-aac53.appspot.com',
    measurementId: 'G-EJ35770TN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaCjmoXN4Vnuj9nbycXfpEQqMBwWxQFek',
    appId: '1:726361486193:android:e121e9d032b7dbc3ccfcd0',
    messagingSenderId: '726361486193',
    projectId: 'budget-buddy-aac53',
    storageBucket: 'budget-buddy-aac53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdZmpKAY9eA-hgALRiZhHk7tcNkuCaB4Y',
    appId: '1:726361486193:ios:eb205f23c0508aa8ccfcd0',
    messagingSenderId: '726361486193',
    projectId: 'budget-buddy-aac53',
    storageBucket: 'budget-buddy-aac53.appspot.com',
    iosClientId: '726361486193-56tbtfgr8lqfrb2svaph26v3o9eqcquv.apps.googleusercontent.com',
    iosBundleId: 'com.prerak.budgetBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdZmpKAY9eA-hgALRiZhHk7tcNkuCaB4Y',
    appId: '1:726361486193:ios:9f59c0ce21749702ccfcd0',
    messagingSenderId: '726361486193',
    projectId: 'budget-buddy-aac53',
    storageBucket: 'budget-buddy-aac53.appspot.com',
    iosClientId: '726361486193-jh4i0ai8kt16ub89p7i86mbp6jl1s2ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.kjsce7',
  );
}
